package interfazgame;

import interfazgame.Dashboard;
import interfazgame.Admin;
import a2z.HelpLogin;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Ventana principal al iniciar la aplicación
 * @author marcos
 * @version final
 */
public class Index extends javax.swing.JFrame {

    private ArrayList<HelpLogin> vLogin = null;

    private int id_user = 0;

  
    public Index() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("A2Z Game");
        this.getContentPane().setBackground(Color.decode("#1f2029"));

        jLabel1.setForeground(Color.decode("#fafafa"));
        jLabel2.setForeground(Color.decode("#fafafa"));
        jLabel3.setForeground(Color.decode("#fafafa"));

        jLabel4.setForeground(Color.decode("#fafafa"));
        jLabel5.setForeground(Color.decode("#fafafa"));
        jLabel6.setForeground(Color.decode("#fafafa"));

        jLabel7.setForeground(Color.decode("#fafafa"));
        jLabel8.setForeground(Color.decode("#fafafa"));
        jLabelLogin.setForeground(Color.decode("#fafafa"));

        jButtonIniciarse.setForeground(Color.BLACK);
        jButtonIniciarse.setBackground(Color.WHITE);

        jButtonRegister_go.setForeground(Color.BLACK);
        jButtonRegister_go.setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin_usuario = new javax.swing.JTextField();
        jPasswordFieldLogin_clave = new javax.swing.JPasswordField();
        jButtonIniciarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRegister_usuario = new javax.swing.JTextField();
        jPasswordFieldRegister_clave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRegister_fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRegister_go = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogin.setText("L O G I N");

        jLabel1.setText("R E G I S T E R");

        jPasswordFieldLogin_clave.setText("jPasswordField1");
        jPasswordFieldLogin_clave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldLogin_claveFocusGained(evt);
            }
        });
        jPasswordFieldLogin_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldLogin_claveMouseClicked(evt);
            }
        });
        jPasswordFieldLogin_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldLogin_claveActionPerformed(evt);
            }
        });

        jButtonIniciarse.setText("GO");
        jButtonIniciarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIniciarseMouseClicked(evt);
            }
        });
        jButtonIniciarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarseActionPerformed(evt);
            }
        });

        jLabel2.setText("User");

        jLabel3.setText("Password");

        jLabel4.setText("User");

        jLabel5.setText("Password");

        jPasswordFieldRegister_clave.setText("jPasswordField1");
        jPasswordFieldRegister_clave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldRegister_claveFocusGained(evt);
            }
        });
        jPasswordFieldRegister_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldRegister_claveMouseClicked(evt);
            }
        });
        jPasswordFieldRegister_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegister_claveActionPerformed(evt);
            }
        });

        jLabel6.setText(" Birthdate");

        jTextFieldRegister_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_fechaActionPerformed(evt);
            }
        });

        jLabel7.setText("dd/mm/yyyy");

        jButtonRegister_go.setText("GO");
        jButtonRegister_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegister_goActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a2z/logojuego.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabelLogin)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldLogin_usuario)
                            .addComponent(jPasswordFieldLogin_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel10)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldRegister_usuario)
                                .addComponent(jPasswordFieldRegister_clave)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel7))
                                .addComponent(jTextFieldRegister_fecha))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonIniciarse)
                .addGap(295, 295, 295)
                .addComponent(jButtonRegister_go)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRegister_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldRegister_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRegister_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLogin_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordFieldLogin_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRegister_go)
                            .addComponent(jButtonIniciarse)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRegister_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_fechaActionPerformed

    private void jButtonIniciarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarseActionPerformed
        // TODO add your handling code here:
        int admin = 0;
       

        String nombre = jTextFieldLogin_usuario.getText();
        String pass = new String(jPasswordFieldLogin_clave.getPassword());
        
        if (nombre.equalsIgnoreCase("") || pass.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Rellene los campos del formulario");
        } else {

            vLogin = bd.conexiones.iniciarse(nombre, pass);
            for (int i = 0; i < vLogin.size(); i++) {
                admin = vLogin.get(i).getAdmin();
                id_user = vLogin.get(i).getCoduser();
                break;
            }
            if (admin == 1) {
                Admin a = new Admin();
                a.setVisible(true);
                this.dispose();
            } else {
                Dashboard d = new Dashboard(id_user);
                d.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonIniciarseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRegister_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegister_goActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldRegister_usuario.getText();
        String pass = new String(jPasswordFieldRegister_clave.getPassword());
        String fecha = jTextFieldRegister_fecha.getText();
        
          if (nombre.equalsIgnoreCase("") || pass.equalsIgnoreCase("") || fecha.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Rellene los campos del formulario");
        } else {
        
        int id_user = bd.conexiones.regitrarse(nombre, pass, fecha);
        if (id_user!=-1){
            Dashboard d = new Dashboard(id_user);
        d.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usuario ya existe");
        }
        
  }  
    }//GEN-LAST:event_jButtonRegister_goActionPerformed

    private void jPasswordFieldLogin_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_claveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordFieldLogin_claveActionPerformed

    private void jPasswordFieldRegister_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_claveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordFieldRegister_claveActionPerformed

    private void jPasswordFieldLogin_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_claveMouseClicked
        // TODO add your handling code here:
        jPasswordFieldLogin_clave.setText("");
    }//GEN-LAST:event_jPasswordFieldLogin_claveMouseClicked

    private void jPasswordFieldRegister_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_claveMouseClicked
        // TODO add your handling code here:
        jPasswordFieldRegister_clave.setText("");
    }//GEN-LAST:event_jPasswordFieldRegister_claveMouseClicked

    private void jButtonIniciarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarseMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jButtonIniciarseMouseClicked

    private void jPasswordFieldLogin_claveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_claveFocusGained
        // TODO add your handling code here:
           jPasswordFieldLogin_clave.setText("");
    }//GEN-LAST:event_jPasswordFieldLogin_claveFocusGained

    private void jPasswordFieldRegister_claveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_claveFocusGained
        // TODO add your handling code here:
         jPasswordFieldRegister_clave.setText("");
    }//GEN-LAST:event_jPasswordFieldRegister_claveFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciarse;
    private javax.swing.JButton jButtonRegister_go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPasswordField jPasswordFieldLogin_clave;
    private javax.swing.JPasswordField jPasswordFieldRegister_clave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldLogin_usuario;
    private javax.swing.JTextField jTextFieldRegister_fecha;
    private javax.swing.JTextField jTextFieldRegister_usuario;
    // End of variables declaration//GEN-END:variables
}
